-- Generated by the Organizer Library (Sat Nov 21 19:14:18 2020)
return {
    [1]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }
}