-- Generated by the Organizer Library (Wed Dec 30 15:55:34 2020)
return {
    [1]={
        ["log_name"]="ifrit ring", 
        ["id"]=27564, 
        ["name"]="ifrit ring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="karieyh ring", 
        ["id"]=27587, 
        ["name"]="karieyh ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="chirich ring +1", 
        ["id"]=26182, 
        ["name"]="chirich ring +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="aptitude mantle +1", 
        ["id"]=27604, 
        ["name"]="aptitude mantle +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }
}