-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

profiles['powder'] = S {
  'prize powder',
}

profiles['garden'] = S {
  'grimmonite',
  'black sole',
  'king truffle',
  'red terrapin',
  'gold carp',
  'bastore bream',
  'pamamas',
  'crayfish',
  'gigant squid',
  'gavial fish',
  'bhefhel marlin',
  'deathball',
  'elshimo newt',
  'felicifruit',
  'black pepper',
  'sage',
  'giant femur',
  'scorpion shell',
  'red rose',
  'cluster ash',
  'igneous rock',
  'red moko grass',
  'king locust',
  'urunday log',
  'black ghost',
  'persikos',
  'zebra eel',
  'rolanberry',
  'bluetail',
  'crescent fish',
  'ca cuong',
  'contortopus',
  'mhaura garlic',
  'bay leaves',
  'mythril ore',
  'ebony log',
  'bone chip',
  'crab shell',
  'bat wing',
  'carnation',
  'tonberry coat',
  'doll shard',
  'habaneros',
  'vanilla',
  'lesser chigoe',
  'saffron blossom',
  'pine nuts',
  'snapping mole',
  'tree cuttings',
  'scorpion claw',
  'rabbit hide',
  'spider web',
  'platinum ore',
  'mahogany log',
  'oak log',
  'ash log',
  'chestnut log',
  'maple log',
  'darksteel ore',
  'kazham peppers',
  'senroh sardine',
  'yayinbaligi',
  'cone calamary',
  'moorish idol',
  'shall shell',
  'three-eyed fish',
  'eggplant',
  'faerie apple',
  'la theine cabbage',
  'pipira',
  'elshimo pachira fruit',
  'walnut',
  'ruddy seema',
  'barnacle',
  'meteorite',
  'insect wing',
  'dragon talon',
  'lilac',
  'darksteel nugget',
  'dragon bone',
  'Derfland pear',
  'san d\'orian carrot',
  'fish mithkabob',
  'copper ore',
  'elm log',
  'walnut log',
  'phrygian ore',
  'dryad root',
  'high-quality scorpion shell',
  'antlion jaw'  
}

profiles.sobek = S {
  'peiste skin',
  'peiste stinger',
  'bugard skin',
  'lizard skin',
  'lizard egg'
}

profiles.sparks = S {
  'acheron shield',
  'prize powder'
}

return profiles