-- Generated by the Organizer Library (Wed Dec 30 15:55:34 2020)
return {
    [1]={
        ["log_name"]="wakido domaru +2", 
        ["id"]=23118, 
        ["name"]="wakido domaru +2", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="flamma gambieras +1", 
        ["id"]=25941, 
        ["name"]="flam. gambieras +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="tatenashi sune-ate +1", 
        ["id"]=25924, 
        ["name"]="tatena. sune. +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="valorous mitts", 
        ["id"]=27139, 
        ["name"]="valorous mitts", 
        ["count"]=1
    }
}