-- Generated by the Organizer Library (Sat Nov 21 19:14:18 2020)
return {
    [1]={
        ["log_name"]="smertrios's mantle", 
        ["count"]=1, 
        ["id"]=26257, 
        ["name"]="smertrios's mantle", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Accuracy+10", 
            [4]="\"Store TP\"+10"
        }
    }, 
    [2]={
        ["log_name"]="valorous mitts", 
        ["id"]=27139, 
        ["name"]="valorous mitts", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="ryuo sune-ate", 
        ["id"]=27471, 
        ["name"]="ryuo sune-ate", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="founder's breastplate", 
        ["id"]=27910, 
        ["name"]="found. breastplate", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="samurai's nodowa +1", 
        ["id"]=25484, 
        ["name"]="sam. nodowa +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="founder's gauntlets", 
        ["id"]=28049, 
        ["name"]="founder's gauntlets", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="wakido kote +2", 
        ["id"]=23185, 
        ["name"]="wakido kote +2", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="valorous mask", 
        ["id"]=25641, 
        ["name"]="valorous mask", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="nepenthe grip +1", 
        ["id"]=22205, 
        ["name"]="nepenthe grip +1", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="ryuo hakama", 
        ["id"]=27300, 
        ["name"]="ryuo hakama", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="flamma zucchetto +2", 
        ["id"]=25569, 
        ["name"]="flam. zucchetto +2", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="ioskeha belt", 
        ["id"]=26333, 
        ["name"]="ioskeha belt", 
        ["count"]=1
    }
}