-- Generated by the Organizer Library (Wed Dec 30 15:55:34 2020)
return {
    [1]={
        ["log_name"]="valorous greaves", 
        ["id"]=27495, 
        ["name"]="valorous greaves", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="kendatsuba samue", 
        ["id"]=26527, 
        ["name"]="ken. samue", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="ioskeha belt", 
        ["id"]=26333, 
        ["name"]="ioskeha belt", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="kendatsuba hakama", 
        ["id"]=25891, 
        ["name"]="ken. hakama", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="infused earring", 
        ["id"]=28475, 
        ["name"]="infused earring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="valorous mask", 
        ["id"]=25641, 
        ["name"]="valorous mask", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="founder's gauntlets", 
        ["id"]=28049, 
        ["name"]="founder's gauntlets", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="samurai's nodowa +1", 
        ["id"]=25484, 
        ["name"]="sam. nodowa +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="smertrios's mantle", 
        ["count"]=1, 
        ["id"]=26257, 
        ["name"]="smertrios's mantle", 
        ["augments"]={
            [1]="STR+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="STR+5", 
            [4]="Weapon skill damage +10%"
        }
    }, 
    [12]={
        ["log_name"]="smertrios's mantle", 
        ["count"]=1, 
        ["id"]=26257, 
        ["name"]="smertrios's mantle", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Accuracy+10", 
            [4]="\"Store TP\"+10"
        }
    }, 
    [13]={
        ["log_name"]="nepenthe grip +1", 
        ["id"]=22205, 
        ["name"]="nepenthe grip +1", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="wakido haidate +2", 
        ["id"]=23252, 
        ["name"]="wakido haidate +2", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="tartarus platemail", 
        ["id"]=26944, 
        ["name"]="tartarus platemail", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="genmei earring", 
        ["id"]=27539, 
        ["name"]="genmei earring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="knobkierrie", 
        ["id"]=22281, 
        ["name"]="knobkierrie", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="Attack+4", 
            [2]="TP Bonus +250"
        }
    }, 
    [19]={
        ["log_name"]="founder's breastplate", 
        ["id"]=27910, 
        ["name"]="found. breastplate", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="wakido kabuto +2", 
        ["id"]=23051, 
        ["name"]="wakido kabuto +2", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="friomisi earring", 
        ["id"]=28514, 
        ["name"]="friomisi earring", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="twilight torque", 
        ["id"]=11625, 
        ["name"]="twilight torque", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="wakido kote +2", 
        ["id"]=23185, 
        ["name"]="wakido kote +2", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="founder's greaves", 
        ["id"]=28330, 
        ["name"]="founder's greaves", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="thrud earring", 
        ["id"]=26107, 
        ["name"]="thrud earring", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="ginsen", 
        ["id"]=21371, 
        ["name"]="ginsen", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="flamma ring", 
        ["id"]=26211, 
        ["name"]="flamma ring", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="mache earring +1", 
        ["id"]=26081, 
        ["name"]="mache earring +1", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="ryuo hakama", 
        ["id"]=27300, 
        ["name"]="ryuo hakama", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="kasuga domaru +1", 
        ["id"]=26921, 
        ["name"]="kasuga domaru +1", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="flamma zucchetto +2", 
        ["id"]=25569, 
        ["name"]="flam. zucchetto +2", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="ryuo sune-ate +1", 
        ["id"]=27472, 
        ["name"]="ryuo sune-ate +1", 
        ["count"]=1
    }, 
    [34]={
        ["id"]=26022, 
        ["name"]="vim torque +1", 
        ["count"]=1, 
        ["log_name"]="vim torque +1"
    }
}