-- Generated by the Organizer Library (Sat Nov 21 19:14:18 2020)
return {
    [1]={
        ["log_name"]="ichigohitofuri", 
        ["count"]=1, 
        ["id"]=21027, 
        ["name"]="ichigohitofuri", 
        ["augments"]={
            [1]="DMG:+30", 
            [2]="STR+20", 
            [3]="Accuracy+15"
        }
    }, 
    [2]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="wakido kabuto +1", 
        ["id"]=27695, 
        ["name"]="wakido kabuto +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="ginsen", 
        ["id"]=21371, 
        ["name"]="ginsen", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="karieyh ring", 
        ["id"]=27587, 
        ["name"]="karieyh ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="Attack+4", 
            [2]="TP Bonus +250"
        }
    }, 
    [8]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="flamma korazin", 
        ["id"]=25779, 
        ["name"]="flamma korazin", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="founder's greaves", 
        ["id"]=28330, 
        ["name"]="founder's greaves", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="flamma gambieras +1", 
        ["id"]=25941, 
        ["name"]="flam. gambieras +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="flamma ring", 
        ["id"]=26211, 
        ["name"]="flamma ring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="mache earring +1", 
        ["id"]=26081, 
        ["name"]="mache earring +1", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="kasuga domaru +1", 
        ["id"]=26921, 
        ["name"]="kasuga domaru +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="ishvara earring", 
        ["id"]=27537, 
        ["name"]="ishvara earring", 
        ["count"]=1
    }
}